version: '3.8'

services:
  pgadmin4:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@example.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    ports:
      - '80:80'

  postgresql:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - '5432:5432'
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
