version: '3.8'

services:

  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"